Repository Kim-Beomjin/CCC-SSDProject, pull requests merged in 2025-07, with the labels that each got.

#20 [#19][Git]Update README.md for Ground Rules
  README.md
Labels: Git

#50 [TDD_RED, GREEN] 13 red create ssd class add ut
  SSDProject/nand.h
  SSDProject/ssd.cpp
  SSDProject/ssd.h
  SSDProject/ssd_test.cpp
Labels: TDD

#53 [#35][TDD_Red/Green] Read After Write 가능 및 TC 추가
  SSDProject/nand.cpp
  SSDProject/nand.h
  SSDProject/nand_test.cpp
Labels: TDD

#83 [TDD]<<1_FullWriteAndReadCompare>> phase 2 - Implement to call writer and reader
  TestShell/testScript.cpp
  TestShell/testScript.h
  TestShell/testScript_test.cpp
Labels: TDD

#92 [TDD]<<2_PartialLBAWrite>> phase 1 - Implement PartialLBAWrite()
  TestShell/testScript.cpp
  TestShell/testScript.h
  TestShell/testScript_test.cpp
Labels: TDD

#108 [#99][feature] read operation using file access
  TestShell/executor.cpp
  TestShell/executor.h
Labels: Feature

#114 [#113][Feature]<<TestScript>> Implement ReadCompare Action
  TestShell/compositExecutor.cpp
  TestShell/compositExecutor.h
  TestShell/compositExecutor_test.cpp
  TestShell/global_config.h
Labels: Feature

#135 [#122][Bugfix][NAND] ostream의 파일 포멧이 맞지 않는 버그 수정
  SSDProject/nand.cpp
Labels: bug

#138 [#137][Bugfix] Fix Invalid ReadCompare Action
  TestShell/compositExecutor.cpp
  TestShell/executor.cpp
Labels: bug

#144 [#142][Refactor] Reorder parameters of execute()
  TestShell/commandParser.cpp
  TestShell/compositExecutor.cpp
  TestShell/compositExecutor.h
  TestShell/compositExecutor_test.cpp
  TestShell/executor.cpp
  TestShell/executor.h
  TestShell/executor_test.cpp
  TestShell/interface.h
Labels: Refactor

#145 [#143][Bugfix] test_shell: fix result message for tc
  TestShell/shell.cpp
  TestShell/shellInterface_test.cpp
Labels: bug

#152 [#136][Feature][HostInterface] TestShell에서 들어오는 Erase 및 Flush 처리 Interface 추가
  SSDProject/hostInterface.cpp
  SSDProject/hostInterface.h
Labels: Feature

#157 [#155][Feature] Flush 및 Buffer의 File 관련 기본 기능
  SSDProject/BufferManager.cpp
  SSDProject/BufferManager.h
  SSDProject/SSDProject.vcxproj
  SSDProject/SSDProject.vcxproj.filters
  SSDProject/global_config.h
  SSDProject/ssd.cpp
Labels: Feature
